// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';

class DbSyncOutbox extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbSyncOutbox(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> commandId = GeneratedColumn<String>(
    'command_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> protocolVersion = GeneratedColumn<int>(
    'protocol_version',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> commandType = GeneratedColumn<String>(
    'command_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> deviceId = GeneratedColumn<String>(
    'device_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> aggregateId = GeneratedColumn<String>(
    'aggregate_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> baseRevision = GeneratedColumn<int>(
    'base_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> payloadJson = GeneratedColumn<String>(
    'payload_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> attemptCount = GeneratedColumn<int>(
    'attempt_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> nextAttemptAtUtc = GeneratedColumn<int>(
    'next_attempt_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> leaseOwner = GeneratedColumn<String>(
    'lease_owner',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> leaseExpiresAtUtc = GeneratedColumn<int>(
    'lease_expires_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> lastFailureCode = GeneratedColumn<String>(
    'last_failure_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> completedAtUtc = GeneratedColumn<int>(
    'completed_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    commandId,
    protocolVersion,
    commandType,
    deviceId,
    aggregateId,
    appUserId,
    workspaceId,
    projectId,
    baseRevision,
    payloadJson,
    createdAtUtc,
    status,
    attemptCount,
    nextAttemptAtUtc,
    leaseOwner,
    leaseExpiresAtUtc,
    lastFailureCode,
    completedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_sync_outbox';
  @override
  Set<GeneratedColumn> get $primaryKey => {commandId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbSyncOutbox createAlias(String alias) {
    return DbSyncOutbox(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(command_id)',
    'CHECK(status IN (\'pending\', \'leased\', \'needs_resolution\', \'permanent_failure\', \'completed\'))',
    'CHECK(attempt_count >= 0)',
    'CHECK(protocol_version > 0 AND base_revision >= 0)',
    'CHECK((app_user_id IS NULL AND workspace_id IS NULL AND project_id IS NULL)OR(app_user_id IS NOT NULL AND length(trim(app_user_id)) > 0 AND workspace_id IS NOT NULL AND length(trim(workspace_id)) > 0 AND project_id IS NOT NULL AND length(trim(project_id)) > 0))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactRecords extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactRecords(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> questionnaireVersionId =
      GeneratedColumn<String>(
        'questionnaire_version_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> occurredAtUtc = GeneratedColumn<int>(
    'occurred_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> occurredTimeZone = GeneratedColumn<String>(
    'occurred_time_zone',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> firstSubmittedAtUtc = GeneratedColumn<int>(
    'first_submitted_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channel = GeneratedColumn<String>(
    'channel',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channelDetail = GeneratedColumn<String>(
    'channel_detail',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> locationKind = GeneratedColumn<String>(
    'location_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> placeName = GeneratedColumn<String>(
    'place_name',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> smallestRegionId = GeneratedColumn<String>(
    'smallest_region_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> regionTreeVersion =
      GeneratedColumn<String>(
        'region_tree_version',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<double> latitude = GeneratedColumn<double>(
    'latitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> longitude = GeneratedColumn<double>(
    'longitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> locationAccuracyMeters =
      GeneratedColumn<double>(
        'location_accuracy_meters',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> reachCount = GeneratedColumn<int>(
    'reach_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> interestLevel = GeneratedColumn<int>(
    'interest_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> currentRevision = GeneratedColumn<int>(
    'current_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> lifecycleStatus = GeneratedColumn<String>(
    'lifecycle_status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    contactId,
    appUserId,
    workspaceId,
    projectId,
    questionnaireVersionId,
    occurredAtUtc,
    occurredTimeZone,
    firstSubmittedAtUtc,
    channel,
    channelDetail,
    locationKind,
    placeName,
    smallestRegionId,
    regionTreeVersion,
    latitude,
    longitude,
    locationAccuracyMeters,
    reachCount,
    interestLevel,
    currentRevision,
    lifecycleStatus,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_records';
  @override
  Set<GeneratedColumn> get $primaryKey => {contactId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactRecords createAlias(String alias) {
    return DbContactRecords(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(contact_id)',
    'CHECK((location_kind = \'resolved\' AND place_name IS NOT NULL AND length(trim(place_name)) > 0 AND smallest_region_id IS NOT NULL AND length(trim(smallest_region_id)) > 0 AND region_tree_version IS NOT NULL AND length(trim(region_tree_version)) > 0)OR(location_kind = \'not_applicable\' AND place_name IS NULL AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude IS NULL AND longitude IS NULL AND location_accuracy_meters IS NULL)OR(location_kind = \'pending_resolution\' AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180 AND(location_accuracy_meters IS NULL OR location_accuracy_meters >= 0)))',
    'CHECK(lifecycle_status IN (\'active\', \'voided\'))',
    'CHECK(reach_count > 0)',
    'CHECK(interest_level BETWEEN 0 AND 4)',
    'CHECK(current_revision > 0)',
    'CHECK(channel IN (\'face_to_face\', \'voice_call\', \'video_call\', \'instant_text\', \'asynchronous_message\', \'mixed\', \'other_direct\'))',
    'CHECK(channel != \'other_direct\' OR(channel_detail IS NOT NULL AND length(trim(channel_detail)) > 0))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbSyncDrainerLeases extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbSyncDrainerLeases(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> leaseName = GeneratedColumn<String>(
    'lease_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> leaseOwner = GeneratedColumn<String>(
    'lease_owner',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> leaseExpiresAtUtc = GeneratedColumn<int>(
    'lease_expires_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    leaseName,
    leaseOwner,
    leaseExpiresAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_sync_drainer_leases';
  @override
  Set<GeneratedColumn> get $primaryKey => {leaseName};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbSyncDrainerLeases createAlias(String alias) {
    return DbSyncDrainerLeases(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(lease_name)',
    'CHECK(length(trim(lease_name)) > 0)',
    'CHECK(length(trim(lease_owner)) > 0)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbSyncScopes extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbSyncScopes(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> serverCursor = GeneratedColumn<String>(
    'server_cursor',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> lastSuccessAtUtc = GeneratedColumn<int>(
    'last_success_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> lastFailureCode = GeneratedColumn<String>(
    'last_failure_code',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> updatedAtUtc = GeneratedColumn<int>(
    'updated_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    appUserId,
    workspaceId,
    projectId,
    serverCursor,
    lastSuccessAtUtc,
    lastFailureCode,
    updatedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_sync_scopes';
  @override
  Set<GeneratedColumn> get $primaryKey => {appUserId, workspaceId, projectId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbSyncScopes createAlias(String alias) {
    return DbSyncScopes(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(app_user_id, workspace_id, project_id)',
    'CHECK(length(trim(app_user_id)) > 0)',
    'CHECK(length(trim(workspace_id)) > 0)',
    'CHECK(length(trim(project_id)) > 0)',
    'CHECK(server_cursor IS NULL OR length(server_cursor) > 0)',
    'CHECK(last_failure_code IS NULL OR length(trim(last_failure_code)) > 0)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactAttempts extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactAttempts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> attemptId = GeneratedColumn<String>(
    'attempt_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> occurredAtUtc = GeneratedColumn<int>(
    'occurred_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> occurredTimeZone = GeneratedColumn<String>(
    'occurred_time_zone',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> firstSubmittedAtUtc = GeneratedColumn<int>(
    'first_submitted_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channel = GeneratedColumn<String>(
    'channel',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channelDetail = GeneratedColumn<String>(
    'channel_detail',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> linkedContactId = GeneratedColumn<String>(
    'linked_contact_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL REFERENCES db_contact_records(contact_id)',
  );
  @override
  List<GeneratedColumn> get $columns => [
    attemptId,
    appUserId,
    workspaceId,
    projectId,
    occurredAtUtc,
    occurredTimeZone,
    firstSubmittedAtUtc,
    channel,
    channelDetail,
    linkedContactId,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_attempts';
  @override
  Set<GeneratedColumn> get $primaryKey => {attemptId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactAttempts createAlias(String alias) {
    return DbContactAttempts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(attempt_id)',
    'CHECK(length(trim(app_user_id)) > 0)',
    'CHECK(length(trim(workspace_id)) > 0)',
    'CHECK(length(trim(project_id)) > 0)',
    'CHECK(length(trim(occurred_time_zone)) > 0)',
    'CHECK(channel IN (\'face_to_face\', \'voice_call\', \'video_call\', \'instant_text\', \'asynchronous_message\', \'mixed\', \'other_direct\'))',
    'CHECK(channel != \'other_direct\' OR(channel_detail IS NOT NULL AND length(trim(channel_detail)) > 0))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactRevisions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactRevisions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> revisionId = GeneratedColumn<String>(
    'revision_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_records(contact_id)',
  );
  late final GeneratedColumn<int> revisionNumber = GeneratedColumn<int>(
    'revision_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> revisionKind = GeneratedColumn<String>(
    'revision_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'submitted\'',
    defaultValue: const CustomExpression('\'submitted\''),
  );
  late final GeneratedColumn<String> revisedByAppUserId =
      GeneratedColumn<String>(
        'revised_by_app_user_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> revisedAtUtc = GeneratedColumn<int>(
    'revised_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> reason = GeneratedColumn<String>(
    'reason',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> occurredAtUtc = GeneratedColumn<int>(
    'occurred_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> occurredTimeZone = GeneratedColumn<String>(
    'occurred_time_zone',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channel = GeneratedColumn<String>(
    'channel',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channelDetail = GeneratedColumn<String>(
    'channel_detail',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> locationKind = GeneratedColumn<String>(
    'location_kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> placeName = GeneratedColumn<String>(
    'place_name',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> smallestRegionId = GeneratedColumn<String>(
    'smallest_region_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> regionTreeVersion =
      GeneratedColumn<String>(
        'region_tree_version',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<double> latitude = GeneratedColumn<double>(
    'latitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> longitude = GeneratedColumn<double>(
    'longitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> locationAccuracyMeters =
      GeneratedColumn<double>(
        'location_accuracy_meters',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> reachCount = GeneratedColumn<int>(
    'reach_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> interestLevel = GeneratedColumn<int>(
    'interest_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    revisionId,
    contactId,
    revisionNumber,
    revisionKind,
    revisedByAppUserId,
    revisedAtUtc,
    reason,
    occurredAtUtc,
    occurredTimeZone,
    channel,
    channelDetail,
    locationKind,
    placeName,
    smallestRegionId,
    regionTreeVersion,
    latitude,
    longitude,
    locationAccuracyMeters,
    reachCount,
    interestLevel,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_revisions';
  @override
  Set<GeneratedColumn> get $primaryKey => {revisionId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {contactId, revisionNumber},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactRevisions createAlias(String alias) {
    return DbContactRevisions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(revision_id)',
    'UNIQUE(contact_id, revision_number)',
    'CHECK(revision_number > 0)',
    'CHECK(revision_kind IN (\'submitted\', \'corrected\', \'voided\'))',
    'CHECK((revision_number = 1 AND revision_kind = \'submitted\' AND reason IS NULL)OR(revision_number > 1 AND revision_kind IN (\'corrected\', \'voided\') AND reason IS NOT NULL AND length(trim(reason)) > 0))',
    'CHECK(reach_count > 0)',
    'CHECK(interest_level BETWEEN 0 AND 4)',
    'CHECK((location_kind = \'resolved\' AND place_name IS NOT NULL AND length(trim(place_name)) > 0 AND smallest_region_id IS NOT NULL AND length(trim(smallest_region_id)) > 0 AND region_tree_version IS NOT NULL AND length(trim(region_tree_version)) > 0)OR(location_kind = \'not_applicable\' AND place_name IS NULL AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude IS NULL AND longitude IS NULL AND location_accuracy_meters IS NULL)OR(location_kind = \'pending_resolution\' AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180 AND(location_accuracy_meters IS NULL OR location_accuracy_meters >= 0)))',
    'CHECK(channel IN (\'face_to_face\', \'voice_call\', \'video_call\', \'instant_text\', \'asynchronous_message\', \'mixed\', \'other_direct\'))',
    'CHECK(channel != \'other_direct\' OR(channel_detail IS NOT NULL AND length(trim(channel_detail)) > 0))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactAnswers extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactAnswers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_records(contact_id)',
  );
  late final GeneratedColumn<int> revisionNumber = GeneratedColumn<int>(
    'revision_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> questionId = GeneratedColumn<String>(
    'question_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> answerState = GeneratedColumn<String>(
    'answer_state',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> answerStateReason =
      GeneratedColumn<String>(
        'answer_state_reason',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> answerType = GeneratedColumn<String>(
    'answer_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> booleanValue = GeneratedColumn<int>(
    'boolean_value',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL CHECK (boolean_value IN (0, 1))',
  );
  late final GeneratedColumn<String> textValue = GeneratedColumn<String>(
    'text_value',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> numberValue = GeneratedColumn<double>(
    'number_value',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> multiChoiceValueJson =
      GeneratedColumn<String>(
        'multi_choice_value_json',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    contactId,
    revisionNumber,
    questionId,
    answerState,
    answerStateReason,
    answerType,
    booleanValue,
    textValue,
    numberValue,
    multiChoiceValueJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_answers';
  @override
  Set<GeneratedColumn> get $primaryKey => {
    contactId,
    revisionNumber,
    questionId,
  };
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactAnswers createAlias(String alias) {
    return DbContactAnswers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(contact_id, revision_number, question_id)',
    'CHECK(revision_number > 0)',
    'CHECK(length(trim(question_id)) > 0)',
    'CHECK(answer_state_reason IS NULL OR(answer_state = \'not_applicable\' AND answer_state_reason = \'rule_skipped\'))',
    'CHECK((answer_state IN (\'unknown\', \'refused\', \'not_applicable\', \'unanswered\') AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_state = \'answered\' AND((answer_type = \'boolean\' AND boolean_value IS NOT NULL AND text_value IS NULL AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_type IN (\'single_choice\', \'ordinal_choice\', \'date\', \'short_text\', \'long_text\') AND boolean_value IS NULL AND text_value IS NOT NULL AND length(text_value) > 0 AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_type = \'number\' AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NOT NULL AND multi_choice_value_json IS NULL)OR(answer_type = \'multi_choice\' AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NULL AND json_valid(multi_choice_value_json) AND json_type(multi_choice_value_json) = \'array\'))))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactRevisionConflicts extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactRevisionConflicts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> conflictId = GeneratedColumn<String>(
    'conflict_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> commandId = GeneratedColumn<String>(
    'command_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_records(contact_id)',
  );
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> baseRevision = GeneratedColumn<int>(
    'base_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> currentRevision = GeneratedColumn<int>(
    'current_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> conflictingFieldsJson =
      GeneratedColumn<String>(
        'conflicting_fields_json',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> questionnaireVersionId =
      GeneratedColumn<String>(
        'questionnaire_version_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> currentRevisionKind =
      GeneratedColumn<String>(
        'current_revision_kind',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> currentRevisedAtUtc = GeneratedColumn<int>(
    'current_revised_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> currentReason = GeneratedColumn<String>(
    'current_reason',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> currentSnapshotJson =
      GeneratedColumn<String>(
        'current_snapshot_json',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> proposedSnapshotJson =
      GeneratedColumn<String>(
        'proposed_snapshot_json',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'pending\'',
    defaultValue: const CustomExpression('\'pending\''),
  );
  late final GeneratedColumn<String> resolutionCommandId =
      GeneratedColumn<String>(
        'resolution_command_id',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> resolvedAtUtc = GeneratedColumn<int>(
    'resolved_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    conflictId,
    commandId,
    contactId,
    appUserId,
    workspaceId,
    projectId,
    baseRevision,
    currentRevision,
    conflictingFieldsJson,
    questionnaireVersionId,
    currentRevisionKind,
    currentRevisedAtUtc,
    currentReason,
    currentSnapshotJson,
    proposedSnapshotJson,
    status,
    resolutionCommandId,
    createdAtUtc,
    resolvedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_revision_conflicts';
  @override
  Set<GeneratedColumn> get $primaryKey => {conflictId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactRevisionConflicts createAlias(String alias) {
    return DbContactRevisionConflicts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(conflict_id)',
    'CHECK(base_revision > 0 AND current_revision > base_revision)',
    'CHECK(current_revision_kind = \'corrected\')',
    'CHECK(status IN (\'pending\', \'resolution_pending\', \'resolved\'))',
    'CHECK((status = \'pending\' AND resolution_command_id IS NULL AND resolved_at_utc IS NULL)OR(status = \'resolution_pending\' AND resolution_command_id IS NOT NULL AND resolved_at_utc IS NULL)OR(status = \'resolved\' AND resolution_command_id IS NOT NULL AND resolved_at_utc IS NOT NULL))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactDrafts extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactDrafts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> draftId = GeneratedColumn<String>(
    'draft_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> appUserId = GeneratedColumn<String>(
    'app_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> workspaceId = GeneratedColumn<String>(
    'workspace_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> questionnaireVersionId =
      GeneratedColumn<String>(
        'questionnaire_version_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<int> createdAtUtc = GeneratedColumn<int>(
    'created_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> updatedAtUtc = GeneratedColumn<int>(
    'updated_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> occurredAtUtc = GeneratedColumn<int>(
    'occurred_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> occurredTimeZone = GeneratedColumn<String>(
    'occurred_time_zone',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> channel = GeneratedColumn<String>(
    'channel',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> channelDetail = GeneratedColumn<String>(
    'channel_detail',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> locationKind = GeneratedColumn<String>(
    'location_kind',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> placeName = GeneratedColumn<String>(
    'place_name',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> smallestRegionId = GeneratedColumn<String>(
    'smallest_region_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> regionTreeVersion =
      GeneratedColumn<String>(
        'region_tree_version',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<double> latitude = GeneratedColumn<double>(
    'latitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> longitude = GeneratedColumn<double>(
    'longitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> locationAccuracyMeters =
      GeneratedColumn<double>(
        'location_accuracy_meters',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> reachCount = GeneratedColumn<int>(
    'reach_count',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> interestLevel = GeneratedColumn<int>(
    'interest_level',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> syncMode = GeneratedColumn<String>(
    'sync_mode',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'account_private\'',
    defaultValue: const CustomExpression('\'account_private\''),
  );
  late final GeneratedColumn<int> localRevision = GeneratedColumn<int>(
    'local_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> serverRevision = GeneratedColumn<int>(
    'server_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<String> sourceAttemptId = GeneratedColumn<String>(
    'source_attempt_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> conflictOfDraftId =
      GeneratedColumn<String>(
        'conflict_of_draft_id',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> abandonedAtUtc = GeneratedColumn<int>(
    'abandoned_at_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> undoUntilUtc = GeneratedColumn<int>(
    'undo_until_utc',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    draftId,
    appUserId,
    workspaceId,
    projectId,
    questionnaireVersionId,
    createdAtUtc,
    updatedAtUtc,
    occurredAtUtc,
    occurredTimeZone,
    channel,
    channelDetail,
    locationKind,
    placeName,
    smallestRegionId,
    regionTreeVersion,
    latitude,
    longitude,
    locationAccuracyMeters,
    reachCount,
    interestLevel,
    syncMode,
    localRevision,
    serverRevision,
    sourceAttemptId,
    conflictOfDraftId,
    abandonedAtUtc,
    undoUntilUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_drafts';
  @override
  Set<GeneratedColumn> get $primaryKey => {draftId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactDrafts createAlias(String alias) {
    return DbContactDrafts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(draft_id)',
    'CHECK(length(trim(app_user_id)) > 0)',
    'CHECK(length(trim(workspace_id)) > 0)',
    'CHECK(length(trim(project_id)) > 0)',
    'CHECK(length(trim(questionnaire_version_id)) > 0)',
    'CHECK(updated_at_utc >= created_at_utc)',
    'CHECK((occurred_at_utc IS NULL AND occurred_time_zone IS NULL)OR(occurred_at_utc IS NOT NULL AND occurred_time_zone IS NOT NULL AND length(trim(occurred_time_zone)) > 0))',
    'CHECK(channel IS NULL OR channel IN (\'face_to_face\', \'voice_call\', \'video_call\', \'instant_text\', \'asynchronous_message\', \'mixed\', \'other_direct\'))',
    'CHECK((location_kind IS NULL AND place_name IS NULL AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude IS NULL AND longitude IS NULL AND location_accuracy_meters IS NULL)OR(location_kind = \'resolved\' AND place_name IS NOT NULL AND length(trim(place_name)) > 0 AND smallest_region_id IS NOT NULL AND length(trim(smallest_region_id)) > 0 AND region_tree_version IS NOT NULL AND length(trim(region_tree_version)) > 0 AND latitude IS NULL AND longitude IS NULL AND location_accuracy_meters IS NULL)OR(location_kind = \'not_applicable\' AND place_name IS NULL AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude IS NULL AND longitude IS NULL AND location_accuracy_meters IS NULL)OR(location_kind = \'pending_resolution\' AND place_name IS NULL AND smallest_region_id IS NULL AND region_tree_version IS NULL AND latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180 AND(location_accuracy_meters IS NULL OR location_accuracy_meters >= 0)))',
    'CHECK(reach_count IS NULL OR reach_count > 0)',
    'CHECK(interest_level IS NULL OR interest_level BETWEEN 0 AND 4)',
    'CHECK(sync_mode IN (\'account_private\', \'device_only\'))',
    'CHECK(local_revision > 0)',
    'CHECK(server_revision >= 0)',
    'CHECK(source_attempt_id IS NULL OR length(trim(source_attempt_id)) > 0)',
    'CHECK(conflict_of_draft_id IS NULL OR length(trim(conflict_of_draft_id)) > 0)',
    'CHECK((abandoned_at_utc IS NULL AND undo_until_utc IS NULL)OR(abandoned_at_utc IS NOT NULL AND undo_until_utc IS NOT NULL AND undo_until_utc >= abandoned_at_utc))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactDraftAnswers extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactDraftAnswers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> draftId = GeneratedColumn<String>(
    'draft_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_drafts(draft_id)',
  );
  late final GeneratedColumn<String> questionId = GeneratedColumn<String>(
    'question_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> answerState = GeneratedColumn<String>(
    'answer_state',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> answerStateReason =
      GeneratedColumn<String>(
        'answer_state_reason',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> answerType = GeneratedColumn<String>(
    'answer_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> booleanValue = GeneratedColumn<int>(
    'boolean_value',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL CHECK (boolean_value IN (0, 1))',
  );
  late final GeneratedColumn<String> textValue = GeneratedColumn<String>(
    'text_value',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> numberValue = GeneratedColumn<double>(
    'number_value',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> multiChoiceValueJson =
      GeneratedColumn<String>(
        'multi_choice_value_json',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  @override
  List<GeneratedColumn> get $columns => [
    draftId,
    questionId,
    answerState,
    answerStateReason,
    answerType,
    booleanValue,
    textValue,
    numberValue,
    multiChoiceValueJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_draft_answers';
  @override
  Set<GeneratedColumn> get $primaryKey => {draftId, questionId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactDraftAnswers createAlias(String alias) {
    return DbContactDraftAnswers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(draft_id, question_id)',
    'CHECK(length(trim(question_id)) > 0)',
    'CHECK(answer_state_reason IS NULL OR(answer_state = \'not_applicable\' AND answer_state_reason = \'rule_skipped\'))',
    'CHECK((answer_state IN (\'unknown\', \'refused\', \'not_applicable\', \'unanswered\') AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_state = \'answered\' AND((answer_type = \'boolean\' AND boolean_value IS NOT NULL AND text_value IS NULL AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_type IN (\'single_choice\', \'ordinal_choice\', \'date\', \'short_text\', \'long_text\') AND boolean_value IS NULL AND text_value IS NOT NULL AND length(text_value) > 0 AND number_value IS NULL AND multi_choice_value_json IS NULL)OR(answer_type = \'number\' AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NOT NULL AND multi_choice_value_json IS NULL)OR(answer_type = \'multi_choice\' AND boolean_value IS NULL AND text_value IS NULL AND number_value IS NULL AND json_valid(multi_choice_value_json) AND json_type(multi_choice_value_json) = \'array\'))))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbUsers extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbUsers(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> userId = GeneratedColumn<String>(
    'user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> username = GeneratedColumn<String>(
    'username',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL UNIQUE',
  );
  late final GeneratedColumn<String> displayName = GeneratedColumn<String>(
    'display_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> email = GeneratedColumn<String>(
    'email',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> phone = GeneratedColumn<String>(
    'phone',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> birthday = GeneratedColumn<int>(
    'birthday',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> gender = GeneratedColumn<String>(
    'gender',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'unknown\'',
    defaultValue: const CustomExpression('\'unknown\''),
  );
  late final GeneratedColumn<String> occupation = GeneratedColumn<String>(
    'occupation',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'\'',
    defaultValue: const CustomExpression('\'\''),
  );
  late final GeneratedColumn<String> contactJson = GeneratedColumn<String>(
    'contact_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'{}\'',
    defaultValue: const CustomExpression('\'{}\''),
  );
  late final GeneratedColumn<int> roleLevel = GeneratedColumn<int>(
    'role_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> cityNamesJson = GeneratedColumn<String>(
    'city_names_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> teamName = GeneratedColumn<String>(
    'team_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> passwordMd5 = GeneratedColumn<String>(
    'password_md5',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> failedLoginCount = GeneratedColumn<int>(
    'failed_login_count',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 0',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> mustChangePassword = GeneratedColumn<int>(
    'must_change_password',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT 0 CHECK (must_change_password IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<int> lockedUntil = GeneratedColumn<int>(
    'locked_until',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> lastSeenAt = GeneratedColumn<int>(
    'last_seen_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> lastFailedLoginAt = GeneratedColumn<int>(
    'last_failed_login_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    userId,
    username,
    displayName,
    email,
    phone,
    birthday,
    gender,
    occupation,
    contactJson,
    roleLevel,
    cityNamesJson,
    teamName,
    passwordMd5,
    status,
    failedLoginCount,
    mustChangePassword,
    lockedUntil,
    lastSeenAt,
    lastFailedLoginAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_users';
  @override
  Set<GeneratedColumn> get $primaryKey => {userId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbUsers createAlias(String alias) {
    return DbUsers(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(user_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbConversationRecords extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbConversationRecords(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> collectorUserId = GeneratedColumn<String>(
    'collector_user_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> cityName = GeneratedColumn<String>(
    'city_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> areaName = GeneratedColumn<String>(
    'area_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT \'unassigned\'',
    defaultValue: const CustomExpression('\'unassigned\''),
  );
  late final GeneratedColumn<String> teamName = GeneratedColumn<String>(
    'team_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> recorderName = GeneratedColumn<String>(
    'recorder_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> personName = GeneratedColumn<String>(
    'person_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> englishName = GeneratedColumn<String>(
    'english_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<double> averageHeartRate = GeneratedColumn<double>(
    'average_heart_rate',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> latitude = GeneratedColumn<double>(
    'latitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> longitude = GeneratedColumn<double>(
    'longitude',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> locationAccuracyMeters =
      GeneratedColumn<double>(
        'location_accuracy_meters',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> locationError = GeneratedColumn<String>(
    'location_error',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> manualPlaceName = GeneratedColumn<String>(
    'manual_place_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> gender = GeneratedColumn<String>(
    'gender',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> identity = GeneratedColumn<String>(
    'identity',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> ageRange = GeneratedColumn<String>(
    'age_range',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> relationshipLevel = GeneratedColumn<int>(
    'relationship_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 1',
    defaultValue: const CustomExpression('1'),
  );
  late final GeneratedColumn<int> interestLevel = GeneratedColumn<int>(
    'interest_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NOT NULL DEFAULT 2',
    defaultValue: const CustomExpression('2'),
  );
  late final GeneratedColumn<int> attitudeLevel = GeneratedColumn<int>(
    'attitude_level',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> notes = GeneratedColumn<String>(
    'notes',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isLocationVerified = GeneratedColumn<int>(
    'is_location_verified',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints:
        'NOT NULL DEFAULT 0 CHECK (is_location_verified IN (0, 1))',
    defaultValue: const CustomExpression('0'),
  );
  late final GeneratedColumn<double> correctedLatitude =
      GeneratedColumn<double>(
        'corrected_latitude',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<double> correctedLongitude =
      GeneratedColumn<double>(
        'corrected_longitude',
        aliasedName,
        true,
        type: DriftSqlType.double,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<String> correctedPlaceName =
      GeneratedColumn<String>(
        'corrected_place_name',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints: 'NULL',
      );
  late final GeneratedColumn<int> correctedAt = GeneratedColumn<int>(
    'corrected_at',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    recordId,
    createdAt,
    collectorUserId,
    cityName,
    areaName,
    teamName,
    recorderName,
    personName,
    englishName,
    averageHeartRate,
    latitude,
    longitude,
    locationAccuracyMeters,
    locationError,
    manualPlaceName,
    gender,
    identity,
    ageRange,
    relationshipLevel,
    interestLevel,
    attitudeLevel,
    notes,
    isLocationVerified,
    correctedLatitude,
    correctedLongitude,
    correctedPlaceName,
    correctedAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_conversation_records';
  @override
  Set<GeneratedColumn> get $primaryKey => {recordId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbConversationRecords createAlias(String alias) {
    return DbConversationRecords(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(record_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbRecordContacts extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbRecordContacts(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> recordId = GeneratedColumn<String>(
    'record_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> channel = GeneratedColumn<String>(
    'channel',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    contactId,
    recordId,
    channel,
    value,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_record_contacts';
  @override
  Set<GeneratedColumn> get $primaryKey => {contactId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbRecordContacts createAlias(String alias) {
    return DbRecordContacts(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(contact_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbAppSettings extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbAppSettings(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> key = GeneratedColumn<String>(
    'key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> value = GeneratedColumn<String>(
    'value',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [key, value];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_app_settings';
  @override
  Set<GeneratedColumn> get $primaryKey => {key};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbAppSettings createAlias(String alias) {
    return DbAppSettings(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY("key")'];
  @override
  bool get dontWriteConstraints => true;
}

class DbSecurityEvents extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbSecurityEvents(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> eventId = GeneratedColumn<String>(
    'event_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> userId = GeneratedColumn<String>(
    'user_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> eventType = GeneratedColumn<String>(
    'event_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> eventDetailJson = GeneratedColumn<String>(
    'event_detail_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> createdAt = GeneratedColumn<int>(
    'created_at',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    eventId,
    userId,
    eventType,
    eventDetailJson,
    createdAt,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_security_events';
  @override
  Set<GeneratedColumn> get $primaryKey => {eventId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbSecurityEvents createAlias(String alias) {
    return DbSecurityEvents(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(event_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbCanonicalRegionVersions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbCanonicalRegionVersions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> regionVersionKey = GeneratedColumn<String>(
    'region_version_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> regionId = GeneratedColumn<String>(
    'region_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> treeVersion = GeneratedColumn<String>(
    'tree_version',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> parentRegionVersionKey =
      GeneratedColumn<String>(
        'parent_region_version_key',
        aliasedName,
        true,
        type: DriftSqlType.string,
        requiredDuringInsert: false,
        $customConstraints:
            'NULL REFERENCES db_canonical_region_versions(region_version_key)',
      );
  late final GeneratedColumn<String> canonicalName = GeneratedColumn<String>(
    'canonical_name',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> kind = GeneratedColumn<String>(
    'kind',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> attributesJson = GeneratedColumn<String>(
    'attributes_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    regionVersionKey,
    regionId,
    treeVersion,
    parentRegionVersionKey,
    canonicalName,
    kind,
    attributesJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_canonical_region_versions';
  @override
  Set<GeneratedColumn> get $primaryKey => {regionVersionKey};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {regionId, treeVersion},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbCanonicalRegionVersions createAlias(String alias) {
    return DbCanonicalRegionVersions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(region_version_key)',
    'UNIQUE(region_id, tree_version)',
    'CHECK(length(trim(region_id)) > 0)',
    'CHECK(length(trim(tree_version)) > 0)',
    'CHECK(length(trim(canonical_name)) > 0)',
    'CHECK(kind IN (\'country\', \'admin_area\', \'city\', \'district\', \'neighborhood\', \'street\', \'institution\', \'venue\', \'other\'))',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbContactRegionAssignments extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbContactRegionAssignments(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> contactId = GeneratedColumn<String>(
    'contact_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_records(contact_id)',
  );
  late final GeneratedColumn<String> regionVersionKey = GeneratedColumn<String>(
    'region_version_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES db_canonical_region_versions(region_version_key)',
  );
  @override
  List<GeneratedColumn> get $columns => [contactId, regionVersionKey];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_contact_region_assignments';
  @override
  Set<GeneratedColumn> get $primaryKey => {contactId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbContactRegionAssignments createAlias(String alias) {
    return DbContactRegionAssignments(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(contact_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbDraftRegionAssignments extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbDraftRegionAssignments(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> draftId = GeneratedColumn<String>(
    'draft_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL REFERENCES db_contact_drafts(draft_id)',
  );
  late final GeneratedColumn<String> regionVersionKey = GeneratedColumn<String>(
    'region_version_key',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES db_canonical_region_versions(region_version_key)',
  );
  @override
  List<GeneratedColumn> get $columns => [draftId, regionVersionKey];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_draft_region_assignments';
  @override
  Set<GeneratedColumn> get $primaryKey => {draftId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbDraftRegionAssignments createAlias(String alias) {
    return DbDraftRegionAssignments(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const ['PRIMARY KEY(draft_id)'];
  @override
  bool get dontWriteConstraints => true;
}

class DbQuestionnaireVersions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbQuestionnaireVersions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> questionnaireVersionId =
      GeneratedColumn<String>(
        'questionnaire_version_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> versionNumber = GeneratedColumn<int>(
    'version_number',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> status = GeneratedColumn<String>(
    'status',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> installedAtUtc = GeneratedColumn<int>(
    'installed_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    questionnaireVersionId,
    projectId,
    versionNumber,
    status,
    installedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_questionnaire_versions';
  @override
  Set<GeneratedColumn> get $primaryKey => {questionnaireVersionId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {projectId, versionNumber},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbQuestionnaireVersions createAlias(String alias) {
    return DbQuestionnaireVersions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(questionnaire_version_id)',
    'CHECK(length(trim(questionnaire_version_id)) > 0)',
    'CHECK(length(trim(project_id)) > 0)',
    'CHECK(version_number > 0)',
    'CHECK(status = \'published\')',
    'UNIQUE(project_id, version_number)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbQuestionnaireQuestions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbQuestionnaireQuestions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String>
  questionnaireVersionId = GeneratedColumn<String>(
    'questionnaire_version_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES db_questionnaire_versions(questionnaire_version_id)',
  );
  late final GeneratedColumn<String> questionId = GeneratedColumn<String>(
    'question_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> position = GeneratedColumn<int>(
    'position',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> prompt = GeneratedColumn<String>(
    'prompt',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> questionType = GeneratedColumn<String>(
    'question_type',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> isRequired = GeneratedColumn<int>(
    'is_required',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (is_required IN (0, 1))',
  );
  late final GeneratedColumn<int> allowUnknown = GeneratedColumn<int>(
    'allow_unknown',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (allow_unknown IN (0, 1))',
  );
  late final GeneratedColumn<int> allowRefused = GeneratedColumn<int>(
    'allow_refused',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (allow_refused IN (0, 1))',
  );
  late final GeneratedColumn<int> allowNotApplicable = GeneratedColumn<int>(
    'allow_not_applicable',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (allow_not_applicable IN (0, 1))',
  );
  late final GeneratedColumn<int> minimumSelections = GeneratedColumn<int>(
    'minimum_selections',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> maximumSelections = GeneratedColumn<int>(
    'maximum_selections',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> numberKind = GeneratedColumn<String>(
    'number_kind',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> unit = GeneratedColumn<String>(
    'unit',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> minimum = GeneratedColumn<double>(
    'minimum',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<double> maximum = GeneratedColumn<double>(
    'maximum',
    aliasedName,
    true,
    type: DriftSqlType.double,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> maximumLength = GeneratedColumn<int>(
    'maximum_length',
    aliasedName,
    true,
    type: DriftSqlType.int,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<String> displayRuleJson = GeneratedColumn<String>(
    'display_rule_json',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    questionnaireVersionId,
    questionId,
    position,
    prompt,
    questionType,
    isRequired,
    allowUnknown,
    allowRefused,
    allowNotApplicable,
    minimumSelections,
    maximumSelections,
    numberKind,
    unit,
    minimum,
    maximum,
    maximumLength,
    displayRuleJson,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_questionnaire_questions';
  @override
  Set<GeneratedColumn> get $primaryKey => {questionnaireVersionId, questionId};
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {questionnaireVersionId, position},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbQuestionnaireQuestions createAlias(String alias) {
    return DbQuestionnaireQuestions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(questionnaire_version_id, question_id)',
    'CHECK(length(trim(question_id)) > 0)',
    'CHECK(position > 0)',
    'CHECK(length(trim(prompt)) > 0)',
    'CHECK(question_type IN (\'boolean\', \'single_choice\', \'ordinal_choice\', \'multi_choice\', \'number\', \'date\', \'short_text\', \'long_text\'))',
    'CHECK((question_type = \'multi_choice\' AND minimum_selections > 0 AND maximum_selections >= minimum_selections)OR(question_type <> \'multi_choice\' AND minimum_selections IS NULL AND maximum_selections IS NULL))',
    'CHECK((question_type = \'number\' AND number_kind IN (\'integer\', \'decimal\') AND(minimum IS NULL OR maximum IS NULL OR minimum <= maximum))OR(question_type <> \'number\' AND number_kind IS NULL AND unit IS NULL AND minimum IS NULL AND maximum IS NULL))',
    'CHECK((question_type IN (\'short_text\', \'long_text\') AND maximum_length > 0)OR(question_type NOT IN (\'short_text\', \'long_text\') AND maximum_length IS NULL))',
    'CHECK(display_rule_json IS NULL OR(json_valid(display_rule_json) AND json_type(display_rule_json) = \'object\'))',
    'UNIQUE(questionnaire_version_id, position)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbQuestionnaireOptions extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbQuestionnaireOptions(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String>
  questionnaireVersionId = GeneratedColumn<String>(
    'questionnaire_version_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints:
        'NOT NULL REFERENCES db_questionnaire_versions(questionnaire_version_id)',
  );
  late final GeneratedColumn<String> questionId = GeneratedColumn<String>(
    'question_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> optionId = GeneratedColumn<String>(
    'option_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> position = GeneratedColumn<int>(
    'position',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> label = GeneratedColumn<String>(
    'label',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    questionnaireVersionId,
    questionId,
    optionId,
    position,
    label,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_questionnaire_options';
  @override
  Set<GeneratedColumn> get $primaryKey => {
    questionnaireVersionId,
    questionId,
    optionId,
  };
  @override
  List<Set<GeneratedColumn>> get uniqueKeys => [
    {questionnaireVersionId, questionId, position},
  ];
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbQuestionnaireOptions createAlias(String alias) {
    return DbQuestionnaireOptions(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(questionnaire_version_id, question_id, option_id)',
    'CHECK(length(trim(question_id)) > 0)',
    'CHECK(length(trim(option_id)) > 0)',
    'CHECK(position > 0)',
    'CHECK(length(trim(label)) > 0)',
    'UNIQUE(questionnaire_version_id, question_id, position)',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DbQuestionnaireDraftWorkingCopies extends Table with TableInfo {
  @override
  final GeneratedDatabase attachedDatabase;
  final String? _alias;
  DbQuestionnaireDraftWorkingCopies(this.attachedDatabase, [this._alias]);
  late final GeneratedColumn<String> questionnaireDraftId =
      GeneratedColumn<String>(
        'questionnaire_draft_id',
        aliasedName,
        false,
        type: DriftSqlType.string,
        requiredDuringInsert: true,
        $customConstraints: 'NOT NULL',
      );
  late final GeneratedColumn<String> projectId = GeneratedColumn<String>(
    'project_id',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> sourceVersionId = GeneratedColumn<String>(
    'source_version_id',
    aliasedName,
    true,
    type: DriftSqlType.string,
    requiredDuringInsert: false,
    $customConstraints: 'NULL',
  );
  late final GeneratedColumn<int> baseRevision = GeneratedColumn<int>(
    'base_revision',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<String> definitionJson = GeneratedColumn<String>(
    'definition_json',
    aliasedName,
    false,
    type: DriftSqlType.string,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  late final GeneratedColumn<int> hasLocalChanges = GeneratedColumn<int>(
    'has_local_changes',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL CHECK (has_local_changes IN (0, 1))',
  );
  late final GeneratedColumn<int> updatedAtUtc = GeneratedColumn<int>(
    'updated_at_utc',
    aliasedName,
    false,
    type: DriftSqlType.int,
    requiredDuringInsert: true,
    $customConstraints: 'NOT NULL',
  );
  @override
  List<GeneratedColumn> get $columns => [
    questionnaireDraftId,
    projectId,
    sourceVersionId,
    baseRevision,
    definitionJson,
    hasLocalChanges,
    updatedAtUtc,
  ];
  @override
  String get aliasedName => _alias ?? actualTableName;
  @override
  String get actualTableName => $name;
  static const String $name = 'db_questionnaire_draft_working_copies';
  @override
  Set<GeneratedColumn> get $primaryKey => {questionnaireDraftId};
  @override
  Never map(Map<String, dynamic> data, {String? tablePrefix}) {
    throw UnsupportedError('TableInfo.map in schema verification code');
  }

  @override
  DbQuestionnaireDraftWorkingCopies createAlias(String alias) {
    return DbQuestionnaireDraftWorkingCopies(attachedDatabase, alias);
  }

  @override
  List<String> get customConstraints => const [
    'PRIMARY KEY(questionnaire_draft_id)',
    'CHECK(length(trim(questionnaire_draft_id)) > 0)',
    'CHECK(length(trim(project_id)) > 0)',
    'CHECK(base_revision > 0)',
    'CHECK(json_valid(definition_json) AND json_type(definition_json) = \'object\')',
  ];
  @override
  bool get dontWriteConstraints => true;
}

class DatabaseAtV15 extends GeneratedDatabase {
  DatabaseAtV15(QueryExecutor e) : super(e);
  late final DbSyncOutbox dbSyncOutbox = DbSyncOutbox(this);
  late final DbContactRecords dbContactRecords = DbContactRecords(this);
  late final DbSyncDrainerLeases dbSyncDrainerLeases = DbSyncDrainerLeases(
    this,
  );
  late final DbSyncScopes dbSyncScopes = DbSyncScopes(this);
  late final DbContactAttempts dbContactAttempts = DbContactAttempts(this);
  late final DbContactRevisions dbContactRevisions = DbContactRevisions(this);
  late final DbContactAnswers dbContactAnswers = DbContactAnswers(this);
  late final DbContactRevisionConflicts dbContactRevisionConflicts =
      DbContactRevisionConflicts(this);
  late final DbContactDrafts dbContactDrafts = DbContactDrafts(this);
  late final DbContactDraftAnswers dbContactDraftAnswers =
      DbContactDraftAnswers(this);
  late final Index contactDraftsOwnerUpdated = Index(
    'contact_drafts_owner_updated',
    'CREATE INDEX contact_drafts_owner_updated ON db_contact_drafts (app_user_id, abandoned_at_utc, updated_at_utc)',
  );
  late final Index contactRecordsPersonalPeriod = Index(
    'contact_records_personal_period',
    'CREATE INDEX contact_records_personal_period ON db_contact_records (app_user_id, workspace_id, project_id, occurred_at_utc)',
  );
  late final Index contactAttemptsPersonalPeriod = Index(
    'contact_attempts_personal_period',
    'CREATE INDEX contact_attempts_personal_period ON db_contact_attempts (app_user_id, workspace_id, project_id, occurred_at_utc)',
  );
  late final Index syncOutboxReady = Index(
    'sync_outbox_ready',
    'CREATE INDEX sync_outbox_ready ON db_sync_outbox (status, next_attempt_at_utc, created_at_utc)',
  );
  late final Index syncOutboxAggregateOrder = Index(
    'sync_outbox_aggregate_order',
    'CREATE INDEX sync_outbox_aggregate_order ON db_sync_outbox (aggregate_id, created_at_utc)',
  );
  late final Index contactRevisionConflictsOwnerContact = Index(
    'contact_revision_conflicts_owner_contact',
    'CREATE INDEX contact_revision_conflicts_owner_contact ON db_contact_revision_conflicts (app_user_id, contact_id, status)',
  );
  late final DbUsers dbUsers = DbUsers(this);
  late final DbConversationRecords dbConversationRecords =
      DbConversationRecords(this);
  late final DbRecordContacts dbRecordContacts = DbRecordContacts(this);
  late final DbAppSettings dbAppSettings = DbAppSettings(this);
  late final DbSecurityEvents dbSecurityEvents = DbSecurityEvents(this);
  late final DbCanonicalRegionVersions dbCanonicalRegionVersions =
      DbCanonicalRegionVersions(this);
  late final DbContactRegionAssignments dbContactRegionAssignments =
      DbContactRegionAssignments(this);
  late final DbDraftRegionAssignments dbDraftRegionAssignments =
      DbDraftRegionAssignments(this);
  late final DbQuestionnaireVersions dbQuestionnaireVersions =
      DbQuestionnaireVersions(this);
  late final DbQuestionnaireQuestions dbQuestionnaireQuestions =
      DbQuestionnaireQuestions(this);
  late final DbQuestionnaireOptions dbQuestionnaireOptions =
      DbQuestionnaireOptions(this);
  late final DbQuestionnaireDraftWorkingCopies
  dbQuestionnaireDraftWorkingCopies = DbQuestionnaireDraftWorkingCopies(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    dbSyncOutbox,
    dbContactRecords,
    dbSyncDrainerLeases,
    dbSyncScopes,
    dbContactAttempts,
    dbContactRevisions,
    dbContactAnswers,
    dbContactRevisionConflicts,
    dbContactDrafts,
    dbContactDraftAnswers,
    contactDraftsOwnerUpdated,
    contactRecordsPersonalPeriod,
    contactAttemptsPersonalPeriod,
    syncOutboxReady,
    syncOutboxAggregateOrder,
    contactRevisionConflictsOwnerContact,
    dbUsers,
    dbConversationRecords,
    dbRecordContacts,
    dbAppSettings,
    dbSecurityEvents,
    dbCanonicalRegionVersions,
    dbContactRegionAssignments,
    dbDraftRegionAssignments,
    dbQuestionnaireVersions,
    dbQuestionnaireQuestions,
    dbQuestionnaireOptions,
    dbQuestionnaireDraftWorkingCopies,
  ];
  @override
  int get schemaVersion => 15;
}
