#!/usr/bin/env bash

set -euo pipefail

# Two independent sessions exercise the 0067 lineage lock.  The setup uses
# committed synthetic 6BE-concurrency rows because the normal fixture is
# rolled back before this script runs; no report is generated by this check.
: "${DATABASE_URL:?请设置 DATABASE_URL，例如 postgresql://user:password@host/database}"

psql_command="${PSQL_COMMAND:-psql}"
if ! command -v "${psql_command}" >/dev/null 2>&1; then
  echo '找不到 psql；请安装 PostgreSQL client 或设置 PSQL_COMMAND。' >&2
  exit 1
fi

export PGOPTIONS="${PGOPTIONS:-} -c statement_timeout=30000 -c lock_timeout=15000"

run_psql() {
  "${psql_command}" "${DATABASE_URL}" \
    --no-psqlrc \
    --set=ON_ERROR_STOP=1 \
    "$@"
}

temporary_directory="$(mktemp -d)"
race_first_pid=''
race_second_pid=''
replacement_first_pid=''
replacement_revoke_pid=''
revoke_first_pid=''
revoke_replacement_pid=''

cleanup() {
  for pid in \
    "${race_first_pid}" \
    "${race_second_pid}" \
    "${replacement_first_pid}" \
    "${replacement_revoke_pid}" \
    "${revoke_first_pid}" \
    "${revoke_replacement_pid}"; do
    if [[ -n "${pid}" ]] && kill -0 "${pid}" >/dev/null 2>&1; then
      kill "${pid}" >/dev/null 2>&1 || true
    fi
    if [[ -n "${pid}" ]]; then
      wait "${pid}" >/dev/null 2>&1 || true
    fi
  done
  rm -f "${temporary_directory}"/*.out
  rmdir "${temporary_directory}"
}
trap cleanup EXIT

wait_for_lock_holder() {
  local lock_name="$1"
  local first_pid="$2"
  local first_output="$3"
  local probe

  for _ in $(seq 1 100); do
    probe="$(run_psql --tuples-only --no-align --command="
      WITH lock_probe AS (
        SELECT pg_try_advisory_lock(
          hashtextextended('${lock_name}', 0)
        ) AS acquired
      )
      SELECT CASE
        WHEN acquired THEN NOT pg_advisory_unlock(
          hashtextextended('${lock_name}', 0)
        )
        ELSE true
      END
      FROM lock_probe;
    " | tr -d '[:space:]')"
    if [[ "${probe}" == 't' ]]; then
      return
    fi
    sleep 0.1
  done

  kill "${first_pid}" >/dev/null 2>&1 || true
  wait "${first_pid}" >/dev/null 2>&1 || true
  echo "没有观察到并发 ready lock：${lock_name}" >&2
  sed -n '1,160p' "${first_output}" >&2
  exit 1
}

wait_for_lock_waiter() {
  local lock_name="$1"
  local waiting_pid="$2"
  local waiting_output="$3"
  local waiting

  for _ in $(seq 1 100); do
    waiting="$(run_psql --tuples-only --no-align --command="
      WITH lock_key AS (
        SELECT
          ((hashtextextended('${lock_name}', 0) >> 32)
            & 4294967295)::bigint AS classid,
          (hashtextextended('${lock_name}', 0)
            & 4294967295)::bigint AS objid
      )
      SELECT EXISTS (
        SELECT 1
        FROM pg_locks AS lock_row
        CROSS JOIN lock_key
        WHERE lock_row.locktype = 'advisory'
          AND NOT lock_row.granted
          AND lock_row.classid::bigint = lock_key.classid
          AND lock_row.objid::bigint = lock_key.objid
      );
    " | tr -d '[:space:]')"
    if [[ "${waiting}" == 't' ]]; then
      return
    fi
    if ! kill -0 "${waiting_pid}" >/dev/null 2>&1; then
      echo '并发等待会话过早退出。' >&2
      sed -n '1,160p' "${waiting_output}" >&2
      exit 1
    fi
    sleep 0.1
  done

  kill "${waiting_pid}" >/dev/null 2>&1 || true
  wait "${waiting_pid}" >/dev/null 2>&1 || true
  echo "没有观察到并发等待 lock：${lock_name}" >&2
  sed -n '1,160p' "${waiting_output}" >&2
  exit 1
}

lineage_lock_name='management-report-snapshot-replacement-lineage:6bec3000-0000-4000-8000-000000000001:management-report:contact_sessions_by_channel_two_periods'
replacement_user_one='6bec1000-0000-4000-8000-000000000001'
replacement_user_two='6bec1000-0000-4000-8000-000000000002'
replacement_workspace='6bec2000-0000-4000-8000-000000000001'
replacement_project='6bec3000-0000-4000-8000-000000000001'
replacement_org_membership_one='6bec4000-0000-4000-8000-000000000001'
replacement_org_membership_two='6bec4000-0000-4000-8000-000000000002'
replacement_project_membership_one='6bec5000-0000-4000-8000-000000000001'
replacement_project_membership_two='6bec5000-0000-4000-8000-000000000002'
replacement_capability_one='6bec6000-0000-4000-8000-000000000001'
replacement_capability_two='6bec6000-0000-4000-8000-000000000002'

organization_lock_one="organization-membership:${replacement_workspace}:${replacement_user_one}"
project_lock_one="project-membership:${replacement_project}:${replacement_user_one}"
capability_lock_one="management-report-capability:${replacement_project}:${replacement_user_one}:release_management_reports"
organization_lock_two="organization-membership:${replacement_workspace}:${replacement_user_two}"
project_lock_two="project-membership:${replacement_project}:${replacement_user_two}"
capability_lock_two="management-report-capability:${replacement_project}:${replacement_user_two}:release_management_reports"

echo '建立 6BE-concurrency synthetic trusted-v2 channel snapshots。'
run_psql <<'SQL'
BEGIN;

INSERT INTO app_data.app_users (app_user_id, status) VALUES
  ('6bec1000-0000-4000-8000-000000000001'::uuid, 'active'),
  ('6bec1000-0000-4000-8000-000000000002'::uuid, 'active');

INSERT INTO app_data.workspaces (
  workspace_id, workspace_kind, display_name, deleted_at
) VALUES (
  '6bec2000-0000-4000-8000-000000000001'::uuid,
  'organization',
  '6BE-concurrency organization',
  NULL
);

INSERT INTO app_data.projects (project_id, workspace_id, display_name, status)
VALUES (
  '6bec3000-0000-4000-8000-000000000001'::uuid,
  '6bec2000-0000-4000-8000-000000000001'::uuid,
  '6BE-concurrency project',
  'active'
);

INSERT INTO app_data.organization_memberships (
  organization_membership_id, organization_workspace_id, app_user_id,
  active_from_utc, inactive_from_utc
) VALUES
  (
    '6bec4000-0000-4000-8000-000000000001'::uuid,
    '6bec2000-0000-4000-8000-000000000001'::uuid,
    '6bec1000-0000-4000-8000-000000000001'::uuid,
    '2025-01-01T00:00:00Z', NULL
  ),
  (
    '6bec4000-0000-4000-8000-000000000002'::uuid,
    '6bec2000-0000-4000-8000-000000000001'::uuid,
    '6bec1000-0000-4000-8000-000000000002'::uuid,
    '2025-01-01T00:00:00Z', NULL
  );

INSERT INTO app_data.project_memberships (
  project_membership_id, organization_membership_id, project_id,
  active_from_utc, inactive_from_utc
) VALUES
  (
    '6bec5000-0000-4000-8000-000000000001'::uuid,
    '6bec4000-0000-4000-8000-000000000001'::uuid,
    '6bec3000-0000-4000-8000-000000000001'::uuid,
    '2025-01-01T00:00:00Z', NULL
  ),
  (
    '6bec5000-0000-4000-8000-000000000002'::uuid,
    '6bec4000-0000-4000-8000-000000000002'::uuid,
    '6bec3000-0000-4000-8000-000000000001'::uuid,
    '2025-01-01T00:00:00Z', NULL
  );

INSERT INTO app_data.management_report_capability_grants (
  capability_grant_id, project_membership_id, capability_id,
  active_from_utc, inactive_from_utc
) VALUES
  (
    '6bec6000-0000-4000-8000-000000000001'::uuid,
    '6bec5000-0000-4000-8000-000000000001'::uuid,
    'release_management_reports',
    '2025-01-01T00:00:00Z', NULL
  ),
  (
    '6bec6000-0000-4000-8000-000000000002'::uuid,
    '6bec5000-0000-4000-8000-000000000002'::uuid,
    'release_management_reports',
    '2025-01-01T00:00:00Z', NULL
  );

INSERT INTO app_private.project_reporting_time_zone_versions (
  project_id, version_number, expected_version, change_request_id,
  requested_by_app_user_id, reporting_time_zone, period_boundary_id,
  effective_from_utc, requested_at_utc
) VALUES (
  '6bec3000-0000-4000-8000-000000000001'::uuid,
  1,
  0,
  '6bec9000-0000-4000-8000-000000000001'::uuid,
  '6bec1000-0000-4000-8000-000000000001'::uuid,
  'UTC',
  'iso_week_monday_v1',
  '2025-01-01T00:00:00Z',
  '2025-01-01T00:00:00Z'
);

WITH snapshots(
  snapshot_id,
  release_request_id,
  created_by_app_user_id,
  data_cutoff_utc,
  released_at_utc,
  previous_snapshot_id
) AS (
  VALUES
    (
      '6beca000-0000-4000-8000-000000000001'::uuid,
      '6becb000-0000-4000-8000-000000000001'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-01T00:00:00Z'::timestamptz,
      '2026-01-01T01:00:00Z'::timestamptz,
      NULL::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000002'::uuid,
      '6becb000-0000-4000-8000-000000000002'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-02T00:00:00Z'::timestamptz,
      '2026-01-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000003'::uuid,
      '6becb000-0000-4000-8000-000000000003'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-03T00:00:00Z'::timestamptz,
      '2026-01-03T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000004'::uuid,
      '6becb000-0000-4000-8000-000000000004'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-02-01T00:00:00Z'::timestamptz,
      '2026-02-01T01:00:00Z'::timestamptz,
      NULL::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000005'::uuid,
      '6becb000-0000-4000-8000-000000000005'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-02-02T00:00:00Z'::timestamptz,
      '2026-02-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000004'::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000006'::uuid,
      '6becb000-0000-4000-8000-000000000006'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '2026-03-01T00:00:00Z'::timestamptz,
      '2026-03-01T01:00:00Z'::timestamptz,
      NULL::uuid
    ),
    (
      '6beca000-0000-4000-8000-000000000007'::uuid,
      '6becb000-0000-4000-8000-000000000007'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '2026-03-02T00:00:00Z'::timestamptz,
      '2026-03-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000006'::uuid
    )
), reports AS (
  SELECT
    snapshot.*,
    jsonb_build_object(
      'report_id', 'contact_sessions_by_channel_two_periods',
      'report_version', 1,
      'metric_id', 'contact_sessions',
      'metric_version', 1,
      'dimension', 'channel',
      'query_fingerprint',
        'management-report:contact_sessions_by_channel_two_periods:v1',
      'privacy_policy', 'management_contact_session_privacy_v1',
      'source_scope', 'backend_accepted_contacts',
      'project_id', '6bec3000-0000-4000-8000-000000000001',
      'periods', jsonb_build_object(
        'period_boundary_id', 'iso_week_monday_v1',
        'reporting_time_zone', 'UTC',
        'data_cutoff_utc', to_char(
          snapshot.data_cutoff_utc AT TIME ZONE 'UTC',
          'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'
        ),
        'previous_period', jsonb_build_object(
          'start_utc', '2025-12-01T00:00:00.000Z',
          'until_utc', '2025-12-08T00:00:00.000Z'
        ),
        'current_period', jsonb_build_object(
          'start_utc', '2025-12-08T00:00:00.000Z',
          'until_utc', '2025-12-15T00:00:00.000Z'
        )
      ),
      'cells', (
        SELECT jsonb_agg(
          jsonb_build_object(
            'period_key', cell.period_key,
            'category_key', cell.category_key,
            'cell_order', cell.cell_order,
            'value_count', 10,
            'privacy_status', 'displayed'
          ) ORDER BY cell.cell_order
        )
        FROM (VALUES
          ('previous'::text, 'all'::text, 0),
          ('previous', 'face_to_face', 1),
          ('previous', 'voice_call', 2),
          ('previous', 'video_call', 3),
          ('previous', 'instant_text', 4),
          ('previous', 'asynchronous_message', 5),
          ('previous', 'mixed', 6),
          ('previous', 'other_direct', 7),
          ('current', 'all', 8),
          ('current', 'face_to_face', 9),
          ('current', 'voice_call', 10),
          ('current', 'video_call', 11),
          ('current', 'instant_text', 12),
          ('current', 'asynchronous_message', 13),
          ('current', 'mixed', 14),
          ('current', 'other_direct', 15)
        ) AS cell(period_key, category_key, cell_order)
      )
    ) AS protected_report
  FROM snapshots AS snapshot
)
INSERT INTO app_private.management_report_snapshots (
  snapshot_id, release_request_id, created_by_app_user_id, project_id,
  release_lineage_id, report_id, report_version, query_fingerprint,
  reporting_time_zone, data_cutoff_utc, released_at_utc,
  previous_snapshot_id, source_change_sequence, protected_report
)
SELECT
  snapshot_id,
  release_request_id,
  created_by_app_user_id,
  '6bec3000-0000-4000-8000-000000000001'::uuid,
  'management-report:contact_sessions_by_channel_two_periods',
  'contact_sessions_by_channel_two_periods',
  1,
  'management-report:contact_sessions_by_channel_two_periods:v1',
  'UTC',
  data_cutoff_utc,
  released_at_utc,
  previous_snapshot_id,
  CASE WHEN previous_snapshot_id IS NULL THEN 0 ELSE 1 END,
  protected_report
FROM reports;

WITH attempts(
  release_request_id,
  requested_by_app_user_id,
  data_cutoff_utc,
  requested_at_utc,
  compared_snapshot_id,
  released_snapshot_id,
  result_status,
  shared_period_count,
  assessed_cell_count
) AS (
  VALUES
    (
      '6becb000-0000-4000-8000-000000000001'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-01T00:00:00Z'::timestamptz,
      '2026-01-01T01:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000002'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-02T00:00:00Z'::timestamptz,
      '2026-01-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      '6beca000-0000-4000-8000-000000000002'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000003'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-01-03T00:00:00Z'::timestamptz,
      '2026-01-03T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      '6beca000-0000-4000-8000-000000000003'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000004'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-02-01T00:00:00Z'::timestamptz,
      '2026-02-01T01:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000004'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000005'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '2026-02-02T00:00:00Z'::timestamptz,
      '2026-02-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000004'::uuid,
      '6beca000-0000-4000-8000-000000000005'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000006'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '2026-03-01T00:00:00Z'::timestamptz,
      '2026-03-01T01:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000006'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000007'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '2026-03-02T00:00:00Z'::timestamptz,
      '2026-03-02T01:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000006'::uuid,
      '6beca000-0000-4000-8000-000000000007'::uuid,
      'approved', 2, 16
    )
)
INSERT INTO app_private.management_report_release_attempts (
  release_request_id, requested_by_app_user_id, project_id,
  release_lineage_id, report_id, report_version, query_fingerprint,
  reporting_time_zone, data_cutoff_utc, requested_at_utc,
  source_change_sequence, compared_snapshot_id, released_snapshot_id,
  shared_period_count, assessed_cell_count, result_status, reason_codes,
  result_document
)
SELECT
  attempt.release_request_id,
  attempt.requested_by_app_user_id,
  '6bec3000-0000-4000-8000-000000000001'::uuid,
  'management-report:contact_sessions_by_channel_two_periods',
  'contact_sessions_by_channel_two_periods',
  1,
  'management-report:contact_sessions_by_channel_two_periods:v1',
  'UTC',
  attempt.data_cutoff_utc,
  attempt.requested_at_utc,
  CASE WHEN attempt.compared_snapshot_id IS NULL THEN 0 ELSE 1 END,
  attempt.compared_snapshot_id,
  attempt.released_snapshot_id,
  attempt.shared_period_count,
  attempt.assessed_cell_count,
  attempt.result_status,
  '[]'::jsonb,
  jsonb_build_object(
    'release_contract_id', 'management_report_snapshot_release_v1',
    'release_request_id', attempt.release_request_id,
    'project_id', '6bec3000-0000-4000-8000-000000000001'::uuid,
    'release_lineage_id',
      'management-report:contact_sessions_by_channel_two_periods',
    'report_id', 'contact_sessions_by_channel_two_periods',
    'report_version', 1,
    'query_fingerprint',
      'management-report:contact_sessions_by_channel_two_periods:v1',
    'reporting_time_zone', 'UTC',
    'data_cutoff_utc', to_char(
      attempt.data_cutoff_utc AT TIME ZONE 'UTC',
      'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'
    ),
    'requested_at_utc', to_char(
      attempt.requested_at_utc AT TIME ZONE 'UTC',
      'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'
    ),
    'compared_snapshot_id', attempt.compared_snapshot_id,
    'released_snapshot_id', attempt.released_snapshot_id,
    'shared_period_count', attempt.shared_period_count,
    'assessed_cell_count', attempt.assessed_cell_count,
    'result_status', attempt.result_status,
    'reason_codes', '[]'::jsonb
  )
FROM attempts AS attempt;

WITH attempts(
  release_request_id,
  requested_by_app_user_id,
  organization_membership_id,
  project_membership_id,
  capability_grant_id,
  authorization_reference_at_utc,
  data_cutoff_utc,
  reporting_time_zone_effective_from_utc,
  compared_snapshot_id,
  released_snapshot_id,
  result_status,
  shared_period_count,
  assessed_cell_count
) AS (
  VALUES
    (
      '6becb000-0000-4000-8000-000000000001'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '6bec4000-0000-4000-8000-000000000001'::uuid,
      '6bec5000-0000-4000-8000-000000000001'::uuid,
      '6bec6000-0000-4000-8000-000000000001'::uuid,
      '2026-01-01T00:00:00Z'::timestamptz,
      '2026-01-01T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000002'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '6bec4000-0000-4000-8000-000000000001'::uuid,
      '6bec5000-0000-4000-8000-000000000001'::uuid,
      '6bec6000-0000-4000-8000-000000000001'::uuid,
      '2026-01-02T00:00:00Z'::timestamptz,
      '2026-01-02T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      '6beca000-0000-4000-8000-000000000002'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000003'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '6bec4000-0000-4000-8000-000000000001'::uuid,
      '6bec5000-0000-4000-8000-000000000001'::uuid,
      '6bec6000-0000-4000-8000-000000000001'::uuid,
      '2026-01-03T00:00:00Z'::timestamptz,
      '2026-01-03T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000001'::uuid,
      '6beca000-0000-4000-8000-000000000003'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000004'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '6bec4000-0000-4000-8000-000000000001'::uuid,
      '6bec5000-0000-4000-8000-000000000001'::uuid,
      '6bec6000-0000-4000-8000-000000000001'::uuid,
      '2026-02-01T00:00:00Z'::timestamptz,
      '2026-02-01T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000004'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000005'::uuid,
      '6bec1000-0000-4000-8000-000000000001'::uuid,
      '6bec4000-0000-4000-8000-000000000001'::uuid,
      '6bec5000-0000-4000-8000-000000000001'::uuid,
      '6bec6000-0000-4000-8000-000000000001'::uuid,
      '2026-02-02T00:00:00Z'::timestamptz,
      '2026-02-02T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000004'::uuid,
      '6beca000-0000-4000-8000-000000000005'::uuid,
      'approved', 2, 16
    ),
    (
      '6becb000-0000-4000-8000-000000000006'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '6bec4000-0000-4000-8000-000000000002'::uuid,
      '6bec5000-0000-4000-8000-000000000002'::uuid,
      '6bec6000-0000-4000-8000-000000000002'::uuid,
      '2026-03-01T00:00:00Z'::timestamptz,
      '2026-03-01T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      NULL::uuid,
      '6beca000-0000-4000-8000-000000000006'::uuid,
      'approved_baseline', 0, 0
    ),
    (
      '6becb000-0000-4000-8000-000000000007'::uuid,
      '6bec1000-0000-4000-8000-000000000002'::uuid,
      '6bec4000-0000-4000-8000-000000000002'::uuid,
      '6bec5000-0000-4000-8000-000000000002'::uuid,
      '6bec6000-0000-4000-8000-000000000002'::uuid,
      '2026-03-02T00:00:00Z'::timestamptz,
      '2026-03-02T00:00:00Z'::timestamptz,
      '2025-01-01T00:00:00Z'::timestamptz,
      '6beca000-0000-4000-8000-000000000006'::uuid,
      '6beca000-0000-4000-8000-000000000007'::uuid,
      'approved', 2, 16
    )
)
INSERT INTO app_private.management_report_release_v2_attempts (
  release_request_id, requested_by_app_user_id,
  organization_workspace_id, organization_membership_id,
  project_membership_id, capability_grant_id, capability_id,
  authorization_reference_at_utc, project_id,
  reporting_time_zone_version_number, reporting_time_zone,
  reporting_time_zone_effective_from_utc, data_cutoff_utc,
  release_lineage_id, report_id, report_version, query_fingerprint,
  compared_snapshot_id, released_snapshot_id, delegated_release_request_id,
  result_status, reason_codes, result_document
)
SELECT
  attempt.release_request_id,
  attempt.requested_by_app_user_id,
  '6bec2000-0000-4000-8000-000000000001'::uuid,
  attempt.organization_membership_id,
  attempt.project_membership_id,
  attempt.capability_grant_id,
  'release_management_reports',
  attempt.authorization_reference_at_utc,
  '6bec3000-0000-4000-8000-000000000001'::uuid,
  1,
  'UTC',
  attempt.reporting_time_zone_effective_from_utc,
  attempt.data_cutoff_utc,
  'management-report:contact_sessions_by_channel_two_periods',
  'contact_sessions_by_channel_two_periods',
  1,
  'management-report:contact_sessions_by_channel_two_periods:v1',
  attempt.compared_snapshot_id,
  attempt.released_snapshot_id,
  attempt.release_request_id,
  attempt.result_status,
  '[]'::jsonb,
  jsonb_build_object(
    'release_contract_id', 'trusted_management_report_snapshot_release_v2',
    'release_request_id', attempt.release_request_id,
    'project_id', '6bec3000-0000-4000-8000-000000000001'::uuid,
    'release_lineage_id',
      'management-report:contact_sessions_by_channel_two_periods',
    'report_id', 'contact_sessions_by_channel_two_periods',
    'report_version', 1,
    'query_fingerprint',
      'management-report:contact_sessions_by_channel_two_periods:v1',
    'reporting_time_zone_version_number', 1,
    'reporting_time_zone', 'UTC',
    'data_cutoff_utc', to_char(
      attempt.data_cutoff_utc AT TIME ZONE 'UTC',
      'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'
    ),
    'compared_snapshot_id', attempt.compared_snapshot_id,
    'released_snapshot_id', attempt.released_snapshot_id,
    'result_status', attempt.result_status,
    'reason_codes', '[]'::jsonb
  )
FROM attempts AS attempt;

COMMIT;
SQL

echo '验证同一 active head 的两个 replacement 请求只提交一个。'
race_first_output="${temporary_directory}/race-first.out"
race_second_output="${temporary_directory}/race-second.out"
race_ready_lock='6be-concurrency-race-ready'

run_psql --quiet --command="
  SET statement_timeout = '20s';
  BEGIN;
  SELECT pg_advisory_lock(hashtextextended('${lineage_lock_name}', 0));
  SELECT app_private.declare_management_report_snapshot_replacement_v1(
    '6bec7000-0000-4000-8000-000000000001'::uuid,
    '${replacement_user_one}'::uuid,
    '${replacement_project}'::uuid,
    '6beca000-0000-4000-8000-000000000001'::uuid,
    '6beca000-0000-4000-8000-000000000002'::uuid,
    'contact_revision'
  );
  SELECT pg_advisory_lock(hashtextextended('${race_ready_lock}', 0));
  SELECT pg_sleep(3);
  COMMIT;
  SELECT pg_advisory_unlock(hashtextextended('${lineage_lock_name}', 0));
  SELECT pg_advisory_unlock(hashtextextended('${race_ready_lock}', 0));
" >"${race_first_output}" 2>&1 &
race_first_pid=$!
wait_for_lock_holder "${race_ready_lock}" "${race_first_pid}" "${race_first_output}"

run_psql --quiet --command="
  SET statement_timeout = '20s';
  SELECT app_private.declare_management_report_snapshot_replacement_v1(
    '6bec7000-0000-4000-8000-000000000002'::uuid,
    '${replacement_user_one}'::uuid,
    '${replacement_project}'::uuid,
    '6beca000-0000-4000-8000-000000000001'::uuid,
    '6beca000-0000-4000-8000-000000000003'::uuid,
    'late_accepted_data'
  );
" >"${race_second_output}" 2>&1 &
race_second_pid=$!
wait_for_lock_waiter "${organization_lock_one}" "${race_second_pid}" "${race_second_output}"

race_first_status=0
race_second_status=0
wait "${race_first_pid}" || race_first_status=$?
wait "${race_second_pid}" || race_second_status=$?
if [[ "${race_first_status}" -ne 0 || "${race_second_status}" -eq 0 ]]; then
  echo "同一 active head 并发 replacement 结果错误：first=${race_first_status}, second=${race_second_status}" >&2
  sed -n '1,160p' "${race_first_output}" >&2
  sed -n '1,160p' "${race_second_output}" >&2
  exit 1
fi
if ! grep -q 'no longer an active head' "${race_second_output}"; then
  echo '第二个 replacement 没有以 stale active head 失败关闭。' >&2
  sed -n '1,160p' "${race_second_output}" >&2
  exit 1
fi

race_state="$(run_psql --tuples-only --no-align --field-separator='|' --command="
  SELECT
    count(*)::text,
    count(*) FILTER (
      WHERE replacement_request_id =
        '6bec7000-0000-4000-8000-000000000001'::uuid
    )::text,
    count(*) FILTER (
      WHERE replacement_request_id =
        '6bec7000-0000-0000-0000-000000000002'::uuid
    )::text,
    count(*) FILTER (
      WHERE superseded_snapshot_id =
        '6beca000-0000-4000-8000-000000000001'::uuid
        AND replacement_snapshot_id =
          '6beca000-0000-4000-8000-000000000002'::uuid
    )::text
  FROM app_private.management_report_snapshot_replacements
  WHERE project_id = '${replacement_project}'::uuid;
" | tr -d '[:space:]')"
if [[ "${race_state}" != '1|1|0|1' ]]; then
  echo "active head 并发 replacement 不变量失败：${race_state}" >&2
  exit 1
fi

echo '验证 replacement-first：登记完成后撤权仍能按同一锁顺序提交。'
replacement_first_output="${temporary_directory}/replacement-first.out"
replacement_revoke_output="${temporary_directory}/replacement-revoke.out"
replacement_ready_lock='6be-concurrency-replacement-first-ready'

run_psql --quiet --command="
  SET statement_timeout = '20s';
  BEGIN;
  SELECT app_private.declare_management_report_snapshot_replacement_v1(
    '6bec7000-0000-4000-8000-000000000004'::uuid,
    '${replacement_user_one}'::uuid,
    '${replacement_project}'::uuid,
    '6beca000-0000-4000-8000-000000000004'::uuid,
    '6beca000-0000-4000-8000-000000000005'::uuid,
    'contact_revision'
  );
  SELECT pg_advisory_lock(hashtextextended('${replacement_ready_lock}', 0));
  SELECT pg_sleep(3);
  COMMIT;
  SELECT pg_advisory_unlock(hashtextextended('${replacement_ready_lock}', 0));
" >"${replacement_first_output}" 2>&1 &
replacement_first_pid=$!
wait_for_lock_holder "${replacement_ready_lock}" "${replacement_first_pid}" "${replacement_first_output}"

run_psql --quiet --command="
  SET statement_timeout = '20s';
  BEGIN;
  UPDATE app_data.management_report_capability_grants
  SET inactive_from_utc = clock_timestamp()
  WHERE capability_grant_id = '${replacement_capability_one}'::uuid;
  COMMIT;
" >"${replacement_revoke_output}" 2>&1 &
replacement_revoke_pid=$!
wait_for_lock_waiter "${organization_lock_one}" "${replacement_revoke_pid}" "${replacement_revoke_output}"

replacement_first_status=0
replacement_revoke_status=0
wait "${replacement_first_pid}" || replacement_first_status=$?
wait "${replacement_revoke_pid}" || replacement_revoke_status=$?
if [[ "${replacement_first_status}" -ne 0 || "${replacement_revoke_status}" -ne 0 ]]; then
  echo "replacement-first 锁顺序失败：replacement=${replacement_first_status}, revoke=${replacement_revoke_status}" >&2
  sed -n '1,160p' "${replacement_first_output}" >&2
  sed -n '1,160p' "${replacement_revoke_output}" >&2
  exit 1
fi

replacement_first_state="$(run_psql --tuples-only --no-align --field-separator='|' --command="
  SELECT
    (SELECT count(*) FROM app_private.management_report_snapshot_replacements
      WHERE superseded_snapshot_id =
        '6beca000-0000-4000-8000-000000000004'::uuid),
    (SELECT CASE WHEN inactive_from_utc IS NULL THEN 0 ELSE 1 END
      FROM app_data.management_report_capability_grants
      WHERE capability_grant_id = '${replacement_capability_one}'::uuid);
" | tr -d '[:space:]')"
if [[ "${replacement_first_state}" != '1|1' ]]; then
  echo "replacement-first 最终状态错误：${replacement_first_state}" >&2
  exit 1
fi

echo '验证 revoke-first：提交撤权后 replacement 必须 fail closed。'
revoke_first_output="${temporary_directory}/revoke-first.out"
revoke_replacement_output="${temporary_directory}/revoke-replacement.out"
revoke_ready_lock='6be-concurrency-revoke-first-ready'

run_psql --quiet --command="
  SET statement_timeout = '20s';
  BEGIN;
  SELECT pg_advisory_xact_lock(hashtextextended('${organization_lock_two}', 0));
  SELECT pg_advisory_xact_lock(hashtextextended('${project_lock_two}', 0));
  SELECT pg_advisory_xact_lock(hashtextextended('${capability_lock_two}', 0));
  UPDATE app_data.management_report_capability_grants
  SET inactive_from_utc = clock_timestamp()
  WHERE capability_grant_id = '${replacement_capability_two}'::uuid;
  SELECT pg_advisory_lock(hashtextextended('${revoke_ready_lock}', 0));
  SELECT pg_sleep(3);
  COMMIT;
  SELECT pg_advisory_unlock(hashtextextended('${revoke_ready_lock}', 0));
" >"${revoke_first_output}" 2>&1 &
revoke_first_pid=$!
wait_for_lock_holder "${revoke_ready_lock}" "${revoke_first_pid}" "${revoke_first_output}"

run_psql --quiet --command="
  SET statement_timeout = '20s';
  SELECT app_private.declare_management_report_snapshot_replacement_v1(
    '6bec7000-0000-4000-8000-000000000006'::uuid,
    '${replacement_user_two}'::uuid,
    '${replacement_project}'::uuid,
    '6beca000-0000-4000-8000-000000000006'::uuid,
    '6beca000-0000-4000-8000-000000000007'::uuid,
    'late_accepted_data'
  );
" >"${revoke_replacement_output}" 2>&1 &
revoke_replacement_pid=$!
wait_for_lock_waiter "${organization_lock_two}" "${revoke_replacement_pid}" "${revoke_replacement_output}"

revoke_first_status=0
revoke_replacement_status=0
wait "${revoke_first_pid}" || revoke_first_status=$?
wait "${revoke_replacement_pid}" || revoke_replacement_status=$?
if [[ "${revoke_first_status}" -ne 0 || "${revoke_replacement_status}" -eq 0 ]]; then
  echo "revoke-first 锁顺序失败：revoke=${revoke_first_status}, replacement=${revoke_replacement_status}" >&2
  sed -n '1,160p' "${revoke_first_output}" >&2
  sed -n '1,160p' "${revoke_replacement_output}" >&2
  exit 1
fi
if ! grep -q 'management report authorization forbidden' "${revoke_replacement_output}"; then
  echo '撤权先提交后 replacement 没有 fail closed。' >&2
  sed -n '1,160p' "${revoke_replacement_output}" >&2
  exit 1
fi

revoke_first_state="$(run_psql --tuples-only --no-align --field-separator='|' --command="
  SELECT
    (SELECT count(*) FROM app_private.management_report_snapshot_replacements
      WHERE superseded_snapshot_id =
        '6beca000-0000-4000-8000-000000000006'::uuid),
    (SELECT CASE WHEN inactive_from_utc IS NULL THEN 0 ELSE 1 END
      FROM app_data.management_report_capability_grants
      WHERE capability_grant_id = '${replacement_capability_two}'::uuid);
" | tr -d '[:space:]')"
if [[ "${revoke_first_state}" != '0|1' ]]; then
  echo "revoke-first 最终状态错误：${revoke_first_state}" >&2
  exit 1
fi

echo '6BE replacement concurrency check passed: same-head serialization and replacement/revocation lock ordering hold.'
